// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ntfqeuuicrpwaijhmzbh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50ZnFldXVpY3Jwd2FpamhtemJoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MjQ4NjMsImV4cCI6MjA3NTUwMDg2M30.ry1DLBSXFT3RuvmfcYNKxSCrNRlLjsohVw8ZZFwCD9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});